name: 酒店源采集合并

on:
  schedule:
    - cron: '10 0/24 * * *'        #这里更改自动运行的时间，没这两行的话只能手动运行
  workflow_dispatch:
    分支:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install --upgrade pip
      - name: Install dependencies
        run: pip install selenium requests futures eventlet
      - name: Install dependencies
        run: pip install opencv-python requests
      - name: Install dependencies
        run: pip install Beautifulsoup4 requests
      - name: Install dependencies
        run: pip install translate requests
      #- name: Install dependencies
        #run: pip install ffmpy
      - name: Install dependencies
        run: pip install termcolor
      - name: Install dependencies
        run: pip install func_timeout
      - name: Install dependencies
        run: pip install replace
      - name: Install dependencies
        run: pip install input
      - name: Install dependencies
        run: pip install opencc
      - name: Install dependencies
        run: pip install pypinyin
      - name: Install dependencies
        run: pip install pytz 
      - name: Install dependencies
        run: pip install tqdm

      #- name: Run iptv
        #run: python ${{ github.workspace }}/ceshi.py      #这里更改要运行的py
      - name: Run iptv
        run: python ${{ github.workspace }}/组播py/组播综合.py      #这里更改要运行的py     
     # - name: Run iptv
        #run: python ${{ github.workspace }}/组播py/txt加运行时间.py 
      #- name: Run iptv
        #run: python ${{ github.workspace }}/组播py/txt加运行时间2.py 


      - name: 提交更改
        run: |
          git config --local user.email "actions@126.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit *.txt -m "Add generated file"
          git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
